govuk-one-login/di-account-management-rp-registry

.github/workflows/lint-and-validate-registry.yaml

OLH-2410 - Ensure Linting job is more appropriately named.
Update job name in lint workflow
Accurate naming

OLH-2410 - Ensure Linting job is more appropriately named.

---

.gitignore
clients/iaa.ts
jest.config.ts
package.json
tsconfig.json

Ensure client registry can be imported as a module and demonstrate by using as a centralised library in the backend.
Ensure ts-config generates post compiled output
configure to operate as a module
So that client registry can be used as a module by other services.
Demonstrate module is importable and works by other services.

OLH-2413 - Update Backend to Use Centralized Library

---

src/get-translations.ts
tests/get-translations.test.ts

If there is a hint_text, paragraph1 and paragraph2 field in the transaltions, pass that through in the getTranslations function

OLH-2414 Show the hint text and paragraphs for HMRC clients

---

index.ts

OLH-2437 - Ensure we use the latest version of the library whenever we deploy
Fix issue with exporting types as part of library
So that external modules can use the library
https://govukverify.atlassian.net/browse/OLH-2437

OLH-2437 - Ensure we use the latest version of the library whenever we deploy

---

index.ts
src/filter-clients.ts
src/get-client.ts
src/utils.ts
tests/filter-clients.test.ts

OLH-2460 - Add new function to support getting a subset of client registry based on a filter
OLH-2460 - Add new function to support getting a subset of client registry based on a filter
So that we can start using clientRegistry in frontend for hmrc related features.
https://govukverify.atlassian.net/browse/OLH-2460

OLH-2460 Add ability to return a filtered client array.

---

clients/iaa.ts

OLH-2378 - Update SignedIn URL for Immigration Advice Authority
Update SignedIn URL for Immigration Advice Authority RP
To provide a more user friendly experience for signed in card user
https://govukverify.atlassian.net/browse/OLH-2378
Deploy to dev for UCD review

OLH-2378 - Update SignedIn URL for Immigration Advice Authority

---

clients/oneLoginHome.ts
interfaces/client.interface.ts
interfaces/registry.interface.ts

Fix an issue where One Login Home was appearing in production. By changing the account type to `null` for One Login Home, it will not appear in the account list on frontend, which will exclude it.
This was missed in the requirements gathering stage

fix One Login Home appearing in history|

---

.github/workflows/check-links.yaml
.github/workflows/lint-and-validate-registry.yaml
.husky/pre-commit
Dockerfile
package-lock.json
package.json
scripts/check-links.ts
tests/filter-clients.test.ts
tests/get-client.test.ts

[OLH-2479] Monitor RPs for broken links
Created a github action that runs the check links script every week.
Husky requested to remove some code from the pre-commit file as it will be deprecated in the next version.
Resolved failing tests due to the new isActivityLogEnabled flag. 
Updated Lint test to run unit tests as well.
With the number of RPs onboarding it is difficult to know if the links provided are working when RPs change domains e.g. when they move out of private beta and we need to update it to their new url. 
[OLH-2479]: https://govukverify.atlassian.net/browse/OLH-2479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Olh 2479 monitor for broken service card links

---

clients/oneLoginHome.ts

Add Home as an allowed activity log service. This effectively rolls the feature out to everyone as any user who's logged into Home to view their activity history must by definition have Home in their service history.
The Fraud team have given us the go-ahead to release this feature to all users following our slow rollout trial period. This is the simplest way to do that release that also allows us to roll it back later if we need to. 
[Slack conversation with approval to release.](https://gds.slack.com/archives/C02F70D2LQN/p1744630647115329)

OLH-2566: Enable the activity history for all users

---

clients/dbsSubmitABarringReferral.ts

[OLH-2529] Pass language selection to DBS Submit a Barring Referral
Minor change to pass language selection in URL when I user is redirected to a DBS Submit a Barring Referral.
Review from UCD highlighted that the link does not persist the current selected language.
[OLH-2529]: https://govukverify.atlassian.net/browse/OLH-2529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OLH-2529] Pass language selection to DBS Submit a Barring Referral

---

clients/aas.ts

[OLH-2404] Update AAS production client ID
It seems the production client ID provided to us in Dec 2023 was incorrect. Orchestration have provided an alternative one and have confirmed that the one we had has not been used.
[OLH-2404]: https://govukverify.atlassian.net/browse/OLH-2404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update AAS production client ID provided by Orch

---

clients/index.ts

Export hoDors client. 
So it is available for dependent services. Looks like the export was missed when the client was onboarded.

Export DBS Online Result service so it is available

---

clients/index.ts
clients/securityTokenService.ts

Add Mobile's STS service as an internal client.
So out backend knows not to warn us about these events.
https://govukverify.atlassian.net/browse/ATO-1638

BAU: Add Mobile's STS internal service

---

.gitlint
.husky/commit-msg
README.md

- Added Gitlint config
- Added NVM and Gitlint instructions to README
- Added `commit-msg` Git hook using Husky which pipes the commit message to Gitlint
To ensure commit messages are consistently formatted, including the Jira ticket number
https://govukverify.atlassian.net/browse/OLH-2648

OLH-2648: add gitlint commit-msg hook to standardise commit messages

---

src/filter-clients.ts
src/utils.ts
tests/filter-clients.test.ts

This PR updates the filterClients function so that we resolve environment specific values before filtering. 
Fixes a bug, where you could not filter on environment specific values

OLH-2507 resolve env specific values when filtering clients

---

clients/UKSBS.ts
clients/index.ts

OLH-2755 Home Service Card: UKSBS Ltd (sponsor DSIT): SHARP
Add new transactonal only service for UKSBS Ltd
So that we can onboard a subset of their users to do the setup process of login, but not use it directly after that
https://govukverify.atlassian.net/browse/OLH-2755
https://govukverify.atlassian.net/browse/DIOT-913
Deploy in dev and test to ensure it behaves as expected

OLH-2755 Home Service Card: UKSBS Ltd (sponsor DSIT): SHARP

---

clients/dftConnectivityTool.ts

Update start page description for Connectivity Tool from the Department for Transport

OLH-2765: update start page description for Connectivity Tool from the Department for Transport

---

clients/dfeFindTeacherTrainingCourses.ts

It's been requested that the title for "Find teacher training courses" is updated to "Find teacher training courses in England" on [Services you can use with GOV.UK One Login](https://home.account.gov.uk/services-using-one-login?lng=en).
Before this update:
After this update:
As far as my understanding of the requirements goes, the text for the service card should remain the same.

OLH-2660: Tweak start text for Find teacher training

---

clients/index.ts
clients/nationalSecurityAndInvestments.ts

OLH-2736 Onboard RP: CO: National Security & Investment
Add new RP for public beta
So National Security & Investment can be onboarded
https://govukverify.atlassian.net/browse/OLH-2736
https://govukverify.atlassian.net/browse/DIOT-1154

OLH-2736 Onboard RP: CO: National Security & Investment

---

clients/hoSubmitAPleasureCraftReport.ts
interfaces/client.interface.ts
src/filter-clients.ts
src/utils.ts
tests/filter-clients.test.ts
tests/get-client.test.ts
tests/validate-clients.test.ts

Updates the Client interface to allow certain boolean properties to also accept Date values. The functions for getting and filtering clients have been updated to handle clients with Date properties, and the associated unit tests have been updated to ensure it is working as expected.
To allow us to merge client registry changes to production but not have certain features enabled until a particular date.

OLH-3110: extend boolean properties to allow dates

---

clients/hoSubmitAPleasureCraftReport.ts

Fix the casing of the start text for the `Home Office: Submit a Pleasure Craft Report` client to match the service header and link text

OLH-3060: fix casing of start text
